name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  build-lint-format-type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup-node-and-pnpm

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Format Check
        run: pnpm format:check

      - name: Type Check
        run: pnpm type-check
